- name: Build infrastructure
  environment: "{{ credentials_env }}"
  terraform:
    force_init: yes
    project_path: "{{ tmp_dir }}/{{ infrastructure_dir }}"
    backend_config: "{{ backend_config }}"
    variables:
      public_key: "{{ public_key }}"
  register: tf_output
- name: Register created host
  add_host:
    hostname: 'test_host'
    ansible_ssh_host: "{{ tf_output.outputs['test_host_ip']['value'] }}"
    ansible_ssh_user: 'linux'
    ansible_ssh_private_key_file: "{{ key_path }}"
