---
- when: state != 'absent'
  block:
    - name: Check bastion
      os_server_facts:
        server: "{{ server_fqdn }}"

    - name: Create Server
      os_server:
        state: "{{ state }}"
        auto_ip: false
        availability_zone: "{{ availability_zone | default(omit) }}"
        name: "{{ server_fqdn }}"
        image: "{{ server_image }}"
        flavor: "{{ server_flavor }}"
        key_name: "{{ server_keypair_name }}"
        boot_from_volume: true
        volume_size: "{{ server_volume_size }}"
        network: "{{ server_net }}"
        security_groups: "{{ security_group }}"
        terminate_volume: true
        userdata: "{{ lookup('template', './user-data.j2') }}"
        meta: "group=bastion,groups={{ domain_name }},host-type=bastion,ansible_user={{ server_ssh_user }}"
      register: bastion_server
      when: openstack_servers is not defined or (openstack_servers|length==0)

    # there is no need to attach FIP this way starting from OpenStackSDK==0.30.0
    - os_floating_ip:
        server: "{{ server_fqdn }}"
        floating_ip_address: "{{ fixed_floating_ip | default(omit) }}"
      when: assign_floating_ip|bool

    - name: get server info
      os_server_facts:
        server: "{{ server_fqdn }}"
      when:
        - assign_floating_ip|bool
        - openstack_servers is not defined or (openstack_servers|length==0)

    - name: Convert nets list into dict for bastion address retrieval
      set_fact:
        bastion_ips: "{{ bastion_ips|default({}) | combine( {item['OS-EXT-IPS:type']: item['addr']} ) }}"
      with_items: "{{ openstack_servers[0]['addresses'][server_net] }}"
      when: assign_floating_ip|bool

    # If not
    - name: Convert nets list into dict for bastion address retrieval
      set_fact:
        bastion_ips: "{{ bastion_ips|default({}) | combine( {item['OS-EXT-IPS:type']: item['addr']} ) }}"
      with_items: "{{ bastion_server['server']['addresses'][server_net] }}"
      when: not assign_floating_ip|bool

    - name: Get the access address
      set_fact:
        bastion_interface_ip: "{{ bastion_ips['floating'] | default(bastion_ips['fixed']) }}"

    - name: debug interface IP
      debug:
        var: bastion_interface_ip

    # Wait for the server to really start and become accessible
    - name: Check connectivity to the bastion server
      wait_for:
        port: 22
        host: "{{ bastion_interface_ip }}"
        timeout: 300
      when: assign_floating_ip|bool

    - name: Add the bastion to the inventory
      add_host:
        hostname: "{{ server_fqdn }}"
        ansible_host: "{{ bastion_interface_ip }}"
        ansible_user: "{{ server_ssh_user }}"
        ansible_ssh_private_key_file: "{{ ansible_ssh_private_key_file }}"
        ansible_python_interpreter: "{{ bastion_python | default(omit) }}"
        groups: bastions
      when: assign_floating_ip|bool

- when: state == 'absent'
  block:
    - name: Delete bastion server
      os_server:
        state: absent
        name: "{{ server_fqdn }}"
        delete_fip: "{{ not fixed_floating_ip | default(True) }}"
