- name: 'Wait for host to be available'
  wait_for_connection:
    timeout: 30
- name: Checkout from git
  git:
    repo: "{{ csm_repo }}"
    dest: "{{ csm_home }}"
    version: "{{ csm_version }}"
    force: yes
    depth: 1
- name: 'Debug creadentials'
  debug:
    var: credentials_env
    verbosity: 4

- name: Provisioning with bash
  block:
  - name: Build # noqa 301 305
    environment: "{{ credentials_env }}"
    shell: "{{ start_ssh_agent }} && ./build.sh {{ scenario }} -no-color"
    args:
      chdir: "{{ csm_home }}/scenarios"
    when: scenario_state == 'present'
  - name: Destroy
    environment: "{{ credentials_env }}"
    shell: "{{ start_ssh_agent }} && ./destroy.sh {{ scenario }} -no-color"
    args:
      chdir: "{{ csm_home }}/scenarios"
    when: scenario_state == 'absent'
  when: not bashless

- name: Provisioning with ansible
  block:
  - name: Build
    include: "{{ csm_home }}/playbooks/{{ scenario }}_setup.yml"
    when: scenario_state == 'present'
  - name: Destroy
    include: "{{ csm_home }}/playbooks/{{ scenario }}_destroy.yml"
    when: scenario_state == 'absent'
  when: bashless
