- name: 'Create venv if missing'
  pip:
    name: pip
    virtualenv: "{{ csm_home }}/.venv"
    virtualenv_command: /usr/bin/python3 -m venv
- name: 'Run test.sh for scenario' # noqa 301 305
  environment: "{{ credentials_env }}"
  shell: "{{ start_ssh_agent }} && ./test.sh {{ scenario }}"
  args:
    chdir: "{{ csm_home }}/scenarios"
