---
- name: Download or create shared private key
  block:
  - name: Download/create key  # noqa 301 - get_key is more or less idempotent
    script: "get_key.py --output {{ key_path }} --key key/{{ key_name }}"
    args:
      executable: 'python3'
  - name: Save public key
    set_fact:
      public_key: "{{ item }}"
    with_file:
    - "{{ key_path }}.pub"

- name: Add key pair
  os_keypair:
    state: "{{ state }}"
    name: "{{ key_pair_name }}"
    public_key_file: "{{ key_path }}.pub"

- include_role:
    name: opentelekomcloud.vpc
- include_role:
    name: opentelekomcloud.bastion

- name: Register created host
  add_host:
    hostname: 'test_host'
    ansible_ssh_host: "{{ tf_output.outputs['test_host_ip']['value'] }}"
    ansible_ssh_user: 'linux'
    ansible_ssh_private_key_file: "{{ key_path }}"
