---
- name: Build infrastructure with terraform
  import_playbook: tf_apply.yml

- name: Setup created host
  hosts: test_host
  gather_facts: no
  tasks:
  - name: Wait for host to be up
    wait_for_connection:
      delay: 5
      timeout: 120
  - name: Checkout from git
    git:
      repo: 'https://github.com/opentelekomcloud-infra/customer-service-monitoring'
      dest: "{{ csm_home }}"
      version: "{{ csm_version }}"
      force: yes
      depth: 1
