- name: Destroy test infra
  hosts: local
  vars:
    state: absent
  tasks:
    - name: Remove key pair
      os_keypair:
        state: "{{ state }}"
        name: "{{ key_pair_name }}"
        public_key_file: "{{ key_path }}.pub"
  roles:
  - opentelekomcloud.bastion
  - opentelekomcloud.vpc
