---
- import_playbook: tf_apply.yml

- name: Wait for test host
  hosts: test_host
  gather_facts: no
  tasks:
  - name: Wait for host to be up
    wait_for_connection:
      timeout: 120

- name: Ensure required packages
  hosts: test_host
  become: yes
  roles:
  - role: darkwizard242.terraform  # Make sure required version of terraform is installed
  tasks:
  - name: Ensure python3-venv available
    apt:
      name: python3-venv
      update_cache: yes

- name: Setup created host
  hosts: test_host
  tasks:
  - name: Checkout from git
    git:
      repo: 'https://github.com/opentelekomcloud-infra/customer-service-monitoring'
      dest: "{{ csm_home }}"
      version: "{{ csm_version }}"
      force: yes
      depth: 1
  - name: Install ansible roles  # noqa 301 305
    shell: "ansible-galaxy install -r {{ csm_home }}/requirements.yml"
  - name: Install test host python requirements (including ansible)
    pip:
      name: pip
      virtualenv: "{{ csm_home }}/.venv"
      virtualenv_command: '/usr/bin/python3 -m venv'
