- import_playbook: infrastructure_build.yml

- name: Creation clouds.yaml on test_host
  hosts: test_host
  become: yes
  vars:
    username: "{{ lookup('env', 'TF_username') }}"
    password: "{{ lookup('env', 'TF_password') }}"
    auth_url: https://iam.eu-de.otc.t-systems.com/v3
    user_domain_name: OTC00000000001000000447
    project_name: eu-de_rus
    region_name: eu-de
  tasks:
   - name:  Creation openstack directory
     file:
       path: ~/.config/openstack/
       state: directory
   - name: Filling template of clouds.yaml.j2
     template:
       src: clouds.yaml.j2
       dest: ~/.config/openstack/clouds.yaml

- name: Start scenario 1.5
  hosts: test_host
  vars:
    scenario: scenario1_5
    bashless: yes
  roles:
  - build_scenario
  tasks:
  - name: Path to cron
    cron:
      env: yes
      name: PATH
      value: /usr/local/bin:/usr/bin:/bin
  - name: Environment
    cron:
      env: yes
      name: "{{ item.key }}"
      value: "{{ item.value }}"
    loop: "{{ lookup('dict', credentials_env) }}"
  - name: Schedule scn 1.5 test
    cron:
      name: Scenario 1.5 monitoring
      user: linux
      minute: '*/5'
      job: "{{ start_ssh_agent }} && cd {{ csm_home }}/scenarios && ./test.sh {{ scenario }}"
