---
- name: Install local requirements
  become: yes
  hosts: local
  vars:
    pip_requirements: 'requirements.txt'
    tmp_dir: '/tmp'
  tasks:
  - name: Copy Requirements
    copy:
      src: "{{ pip_requirements }}"
      dest: "{{ tmp_dir }}"
  - name: Install master requirements
    pip:
      executable: pip3
      requirements: "{{ tmp_dir }}/{{ pip_requirements }}"
