---
- name: Install local requirements
  become: yes
  hosts: local
  vars:
    requirements: 'requirements.txt'
    tmp_dir: '/tmp'
  tasks:
  - name: Copy Requirements
    copy:
      src: "{{ requirements }}"
      dest: "{{ tmp_dir }}"
  - name: Install master requirements
    pip:
      executable: pip3
      requirements: "{{ tmp_dir }}/{{ requirements }}"
