---
- import_playbook: infrastructure_build.yml

- name: Install and run delatore
  hosts: test_host
  become: yes
  vars:
    config_path: /tmp/delatore_config.ini
  tasks:
    - name: Update and upgrade apt packages
      apt:
        upgrade: yes
        update_cache: yes

    - name: Install required packages
      apt:
        name:
          - python3-setuptools
          - python3-pip
          - cron
          - build-essential
          - python3-dev

    - name: Install delatore
      pip:
        executable: pip3
        name: delatore

    - name: Write configuration
      template:
        src: delatore_config.ini.j2
        dest: "{{ config_path }}"
        force: yes

    - name: Start delatore
      shell: "nohup /usr/bin/python3 -m delatore --config {{ config_path }} &" # noqa 301 305

- name: Install and setup nginx
  hosts: test_host
  become: yes
  vars_files:
  - "./vars/delatore_nginx_parameters.yml"
  vars:
    certbot_admin_email: "delatore@{{ domain }}"
    certbot_create_if_missing: true
    certbot_auto_renew_user: linux
    certbot_auto_renew_minute: "20"
    certbot_auto_renew_hour: "5"
    certbot_certs:
      - domains:
          - "{{ domain }}"
    nginx_remove_default_vhost: yes
    nginx_vhosts:
    - listen: "443 ssl"
      server_name: "{{ domain }}"
      extra_parameters: "{{ extra_parameters }}"
  roles:
    - role: geerlingguy.certbot
    - role: geerlingguy.nginx
