- name: terraform apply
  hosts: local
  tasks:
  - name: Copy TF directory to /tmp
    copy:
      src: "{{ infrastructure_dir }}"
      dest: "{{ tmp_dir }}"
  - name: Download or create shared private key
    block:
    - name: Download/create key
      script: "get_key.py --output {{ key_path }} --key key/{{ key_name }}"
      args:
        executable: 'python3'
        creates: "{{ key_path }}"
    - name: chmod 600
      file:
        path: "{{ key_path }}"
        mode: 0600
    - name: Get public key
      openssh_keypair:
        path: "{{ key_path }}"
      register: keypair
    - name: Save public key
      set_fact:
        public_key: "{{ keypair.public_key }}"
  - name: Build infrastructure
    environment: "{{ credentials_env }}"
    terraform:
      force_init: yes
      project_path: "{{ tmp_dir }}/{{ infrastructure_dir }}"
      backend_config:
        key: "terraform_state/test_infra"
        bucket: "obs-csm"
        region: "eu-de"
      variables:
        public_key: "{{ public_key }}"
    register: tf_output
  - name: Register created host
    add_host:
      hostname: 'test_host'
      ansible_ssh_host: "{{ tf_output.outputs['test_host_ip']['value'] }}"
      ansible_ssh_user: 'linux'
      ansible_ssh_private_key_file: "{{ key_path }}"
